[package]
name = "noise-lalrpop"
version = "0.1.0"
authors = ["Volker Mische <volker.mische@gmail.com>"]
build = "build.rs"

[build-dependencies]
lalrpop = "0.13.1"

[dependencies]
regex = "0.2.0"
lalrpop-util = "0.13.1"
